site_name: Tidal Telemetry
site_url: https://docs.stevenseboat.org
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - toc.follow  
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.tabs.link

  palette:
    primary: custom
    accent: custom 
    scheme: slate
  font:
    text: Inter
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css

watch:
  - includes

plugins:
  - search
  - open-in-new-tab:
     add_icon: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - abbr
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/stevenseboat
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stevenseboat
    - icon: fontawesome/brands/github
      link: https://github.com/Stevens-Electric-Boatworks
  
    
nav:
  - Home:
    - Introduction: index.md
    - Features: features.md
  - Introduction (Start Here):
    - Intro to Tidal Telemetry: intro/welcome.md
    - System Design: intro/system-design.md
    - TidalCore: intro/tidalcore.md
    - TidalView: intro/tidalview.md
  - Developer Setup:
    - Prerequisites: dev-setup/prerequisites.md
    - TidalCore: dev-setup/tidalcore.md
    - TidalView: dev-setup/tidalview.md
    - TidalShore: dev-setup/tidalshore.md
    - TidalDocs: dev-setup/tidaldocs.md
  - TidalCore:
    - CAN Bus: tidalcore/can-bus.md
    - Networking Configuration: tidalcore/networking-configuration.md
    - Shore Communication Protocol (TODO): tidalcore/shore-protocol.md
    - Fault Management System (TODO): tidalcore/fault-management-system.md
    - Deploying Code Remotely (TODO): tidalcore/deploying-code.md
    - Data Recording (TODO): tidalcore/data-recording.md
  - TidalShore [todo]:
    - TODO: todo
  - TidalView [todo]:
    - TODO: todo
  - Website ↗: https://stevenseboat.org
  - GitHub ↗: https://github.com/Stevens-Electric-Boatworks
  - ROS Documenation ↗: https://docs.ros.org/en/kilted/Tutorials.html
  
