site_name: Tidal Telemetry Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    primary: custom
    accent: custom 
    scheme: slate
  font:
    text: Inter
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/stevenseboat
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stevenseboat
    - icon: fontawesome/brands/github
      link: https://github.com/Stevens-Electric-Boatworks
    
    
nav:
  - Home: index.md
  - Start Here:
    - Start Here: start-here/welcome.md
    - Overall System Design: start-here/overall-system-design.md
    