site_name: Tidal Telemetry Documentation
site_url: https://stevens-electric-boatworks.github.io/tidal-docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - toc.follow  

  palette:
    primary: custom
    accent: custom 
    scheme: slate
  font:
    text: Inter
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/stevenseboat
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stevenseboat
    - icon: fontawesome/brands/github
      link: https://github.com/Stevens-Electric-Boatworks
  
    
nav:
  - Home:
    - Introduction: index.md
    - Features: features.md
  - Start Here:
    - Intro to Tidal Telemetry: start-here/welcome.md
    - Overall System Design: start-here/overall-system-design.md
    - TidalCore: start-here/tidalcore.md
    - TidalView: start-here/tidalview.md
  - TidalCore:
    - Networking Configuration: tidalcore/networking-configuration.md
